#!/usr/bin/env python3
"""Encode the supplied 48px PNGs as GEOS masked, eight-bit LMem bitmaps.

Pillow is only required to regenerate this checked-in header. Native builds
consume the generated header and do not need an image library.

The GEOS default 256-color palette provides a sixteen-level neutral ramp at
indices 0x10..0x1f. No custom palette is embedded or installed. The UI draws
these 48-pixel source bitmaps at a 24-unit logical footprint.
"""
# SPDX-License-Identifier: GPL-3.0-or-later
import argparse
from pathlib import Path
import struct
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SIDES = ('white', 'black')
PIECES = ('king', 'queen', 'rook', 'bishop', 'knight', 'pawn')
# Library/Kernel/Graphics/graphicsTables.asm: defaultPalette's grayscale ramp.
GRAYS = tuple((0x10 + n, 17 * n) for n in range(16))
SIZE = 48


def encode(path):
    with Image.open(path) as source:
        image = source.convert('RGBA')
    if image.size != (SIZE, SIZE):
        raise ValueError(f'{path}: expected a {SIZE}x{SIZE} PNG')
    result = bytearray(struct.pack('<HHBB', SIZE, SIZE, 0, 0x12))
    for y in range(SIZE):
        mask = bytearray((SIZE + 7) // 8)
        pixels = []
        for x in range(SIZE):
            r, g, b, a = image.getpixel((x, y))
            if a >= 128:
                mask[x // 8] |= 0x80 >> (x % 8)
            # Use the nearest neutral palette entry, with no runtime palette.
            value = (r + g + b) / 3
            pixels.append(min(GRAYS, key=lambda item: abs(item[1]-value))[0])
        result += mask
        result += bytes(pixels)
    return result


def generate():
    output = [
        '/* Generated by tools/generate_pieceicons.py; GPL-3.0-or-later. */',
        '/* 48x48, uncompressed BMF_8BIT | BMT_MASK. Each row: mask, pixels. */',
        '/* Default palette indices 0x10..0x1f: neutral shades 0,17,...,255. */',
        '@start ChessPieces, data;',
    ]
    for side in SIDES:
        for piece in PIECES:
            data = encode(ROOT / 'assets/pieces' / f'{side}-{piece}.png')
            name = 'GC' + side.title() + piece.title()
            output.append(f'@chunk byte {name}[] = {{')
            for i in range(0, len(data), 15):
                output.append('    ' + ', '.join(f'0x{v:02x}' for v in data[i:i+15]) + ',')
            output.append('};')
    output += ['@end ChessPieces;', '']
    return '\n'.join(output)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true',
                        help='fail if the checked-in generated source differs')
    args = parser.parse_args()
    generated = generate()
    dest = ROOT / 'src/geos/pieceicons.goh'
    if args.check:
        if not dest.is_file() or dest.read_text() != generated:
            raise SystemExit('pieceicons.goh is stale; run tools/generate_pieceicons.py')
        print('Piece icon source is reproducible (12 native 48x48 masked bitmaps).')
    else:
        dest.write_text(generated)
        print(f'Generated {dest.relative_to(ROOT)}: 12 bitmaps, 2598 bytes each')


if __name__ == '__main__':
    main()
