#!/usr/bin/env python3
"""Verify native icon resources against original artwork after linking.

Reads the executable's GEOS resource directory and LMem handle tables, then
decodes the embedded bitmaps. It deliberately does not import the generators
or treat generated byte arrays as its expected results.

Format references in the supplied SDK: CInclude/graphics.h (Bitmap, BMF_*,
BMT_*), CInclude/lmem.h (LMemBlockHeader), CInclude/Objects/visC.goh
(VisMonikerWithGString, VisMonikerListEntry), CInclude/gstring.h (OpDrawBitmap),
and CInclude/heap.h (HF_*, HAF_*). Mask row sizing and pixel direction are
confirmed by Driver/Video/VidCom/vidcomRaster.asm and VGACom raster routines.

The output preview is a host reconstruction, never a GEOS screenshot.
Requires Python 3 and Pillow. No GEOS SDK is needed to run this verifier.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import struct

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
PIECES = dict(zip('KQRBNPkqrbnp',
    ['white-king', 'white-queen', 'white-rook', 'white-bishop', 'white-knight',
     'white-pawn', 'black-king', 'black-queen', 'black-rook', 'black-bishop',
     'black-knight', 'black-pawn']))
PALETTE = [(0, 0, 0), (0, 0, 170), (0, 170, 0), (0, 170, 170),
           (170, 0, 0), (170, 0, 170), (170, 85, 0), (170, 170, 170),
           (85, 85, 85), (85, 85, 255), (85, 255, 85), (85, 255, 255),
           (255, 85, 85), (255, 85, 255), (255, 255, 85), (255, 255, 255)]
# The next sixteen default-palette entries are the SDK's neutral grayscale
# ramp. This does not change the original application icon's 0..15 indices.
PALETTE += [(17 * n, 17 * n, 17 * n) for n in range(16)]


def require(condition, message):
    if not condition:
        raise ValueError(message)


def word(data, offset):
    return struct.unpack_from('<H', data, offset)[0]


def read_resources(data, link_map):
    require(data[:4] == bytes.fromhex('c745c153'), 'Not a GEOS 2.x executable')
    count, libraries, exports = struct.unpack_from('<HHH', data, 264)
    entries = re.findall(r'^([A-Za-z_][A-Za-z_0-9]*)\s+(\d+)\s+(\d+)\s*$',
                         link_map, re.M)
    require(len(entries) == count, 'Link map does not match resource count')
    table = 344 + 14 * libraries + 4 * exports
    require(table + count * 10 <= len(data), 'Truncated resource directory')
    resources = {}
    for n, (name, map_size, map_relocs) in enumerate(entries):
        size = word(data, table + 2 * n)
        position = struct.unpack_from('<I', data, table + 2 * count + 4 * n)[0] + 256
        reloc_size = word(data, table + 6 * count + 2 * n)
        flags = word(data, table + 8 * count + 2 * n)
        require(size == int(map_size) and reloc_size == 4 * int(map_relocs),
                name + ': link map differs from executable')
        require(position + size <= len(data), name + ': resource out of bounds')
        relocation_offset = position + ((size + 15) // 16) * 16
        require(relocation_offset + reloc_size <= len(data), name + ': relocations out of bounds')
        relocation_records = list(struct.iter_unpack('<BBH',
                                  data[relocation_offset:relocation_offset + reloc_size]))
        resources[name] = dict(id=n, size=size, file_offset=position, flags=flags,
                               relocations=reloc_size // 4,
                               relocation_records=relocation_records,
                               data=data[position:position + size])
    return resources


def read_chunks(resource, icon_resource=True):
    data = resource['data']
    require(resource['flags'] & 8, 'Icon resource is not LMem')
    if icon_resource:
        require(resource['flags'] & 0x40, 'Icon resource is not shared')
        require(resource['flags'] & 0x800, 'Icon resource is not read-only')
        require(not resource['flags'] & 0x80, 'Icon resource unexpectedly fixed')
    require(len(data) >= 16, 'Truncated LMem header')
    handle, table, flags, kind, block_size, count, free_list, total_free = struct.unpack_from('<8H', data)
    require(block_size == len(data), 'LMem size does not match resource')
    require(kind == (0 if icon_resource else 2), 'Unexpected LMem resource kind')
    require(table + count * 2 <= len(data), 'LMem handle table out of bounds')
    result = []
    for i in range(count):
        chunk_handle = table + i * 2
        offset = word(data, chunk_handle)
        if offset in (0, 0xffff):
            continue
        require(2 <= offset <= len(data), 'Chunk pointer out of bounds')
        size = word(data, offset - 2) - 2
        require(size >= 0 and offset + size <= len(data), 'Chunk size out of bounds')
        result.append(dict(handle=chunk_handle, offset=offset, size=size,
                           data=data[offset:offset + size]))
    return result


def decode_bitmap(data):
    require(len(data) >= 6, 'Truncated bitmap header')
    width, height, compact, flags = struct.unpack_from('<HHBB', data)
    require(width > 0 and height > 0, 'Empty bitmap')
    require(compact == 0, 'Expected uncompressed bitmap')
    require(flags in (0, 1, 2, 0x10, 0x11, 0x12), 'Unexpected bitmap format/palette/complex flag')
    bits = (1, 4, 8)[flags & 7]
    mask_bytes = (width + 7) // 8 if flags & 0x10 else 0
    pixel_bytes = (width * bits + 7) // 8
    row_bytes = mask_bytes + pixel_bytes
    require(len(data) == 6 + height * row_bytes, 'Incorrect bitmap byte count')
    indices, alpha = [], []
    for y in range(height):
        row = data[6 + y * row_bytes:6 + (y + 1) * row_bytes]
        for x in range(width):
            alpha.append(bool(row[x // 8] & (0x80 >> (x % 8))) if mask_bytes else True)
            if bits == 8:
                indices.append(row[mask_bytes + x])
            elif bits == 4:
                byte = row[mask_bytes + x // 2]
                indices.append((byte >> 4) if x % 2 == 0 else (byte & 15))
            else:
                # For monochrome draw bitmaps, a 1 is the current foreground
                # color (black in the application GString); a 0 is white.
                bit = bool(row[mask_bytes + x // 8] & (0x80 >> (x % 8)))
                indices.append(0 if bit else 15)
    require(all(index < len(PALETTE) for index in indices),
            'Bitmap uses an unverified default-palette entry')
    image = Image.new('RGBA', (width, height))
    image.putdata([(*PALETTE[index], 255 if opaque else 0)
                   for index, opaque in zip(indices, alpha)])
    return dict(width=width, height=height, bits=bits, masked=bool(mask_bytes),
                indices=indices, alpha=alpha, image=image)


def piece_error(decoded, original):
    if original.size != (decoded['width'], decoded['height']):
        return 'dimensions differ'
    for y in range(original.height):
        for x in range(original.width):
            pixel = original.getpixel((x, y))
            n = y * original.width + x
            if decoded['alpha'][n] != (pixel[3] >= 128):
                return f'alpha mask differs at {x},{y}'
            if pixel[3] >= 128:
                # Compare squared RGB distance independently of the generator's
                # scalar channel-average quantizer. Both select nearest gray.
                distances = [(sum((v - 17 * step)**2 for v in pixel[:3]), step)
                             for step in range(16)]
                expected = 0x10 + min(distances)[1]
                if decoded['indices'][n] != expected:
                    return f'palette index differs at {x},{y}'
    return None


def verify_pieces(resource, source_dir, goc):
    chunks = read_chunks(resource)
    require(len(chunks) == 12, f'Expected 12 piece chunks; found {len(chunks)}')
    decoded = [decode_bitmap(chunk['data']) for chunk in chunks]
    for bitmap in decoded:
        require((bitmap['width'], bitmap['height'], bitmap['bits'], bitmap['masked']) ==
                (48, 48, 8, True), 'Piece must be a masked 48x48 eight-bit bitmap')
        require(set(bitmap['indices']) <= set(range(0x10, 0x20)),
                'Piece uses an index outside the default grayscale ramp')
    images, report, matched = {}, [], set()
    for character, name in PIECES.items():
        source = source_dir / (name + '.png')
        original = Image.open(source).convert('RGBA')
        matches = [i for i, bitmap in enumerate(decoded) if piece_error(bitmap, original) is None]
        require(len(matches) == 1, name + ': absent, ambiguous, or altered embedded bitmap')
        i = matches[0]
        require(i not in matched, name + ': bitmap shared with a different piece')
        matched.add(i)
        symbol = 'GC' + ''.join(part.title() for part in name.split('-'))
        require(re.search(r"case\s+'" + character + r"'\s*:\s*return\s+@" + symbol + r'\s*;', goc),
                character + ': incorrect UI piece-to-chunk source mapping')
        images[character] = decoded[i]['image']
        report.append(dict(piece=name, character=character, source=str(source.relative_to(ROOT)),
                           chunk_handle=chunks[i]['handle'], resource_offset=chunks[i]['offset'],
                           width=decoded[i]['width'], height=decoded[i]['height'],
                           bits_per_pixel=decoded[i]['bits'], native_bitmap_bytes=chunks[i]['size'],
                           opaque_pixels=sum(decoded[i]['alpha']),
                           pixels_checked=decoded[i]['width'] * decoded[i]['height'],
                           native_bitmap_sha256=hashlib.sha256(chunks[i]['data']).hexdigest(),
                           source_sha256=hashlib.sha256(source.read_bytes()).hexdigest()))
    require('default:return 0;' in goc, 'Empty or unknown square does not return no bitmap')
    return images, report


def verify_color_policy(bitmap, original):
    """Check each actual encoded choice against the error-diffusion contract.

    Unlike the generator, this does not produce packed bits or an expected
    bitmap. It reads source pixels through Pillow and accumulates errors from
    the actual native indices, checking every choice as the scan proceeds.
    """
    width, height = original.size
    errors = [[[0.0] * 3 for x in range(width)] for y in range(height)]
    for y in range(height):
        order = list(range(width))
        if y & 1:
            order.reverse()
        step = -1 if y & 1 else 1
        for x in order:
            n = y * width + x
            if not bitmap['alpha'][n]:
                continue
            source = original.getpixel((x, y))
            value = [min(255, max(0, source[c] + errors[y][x][c])) for c in range(3)]
            actual = bitmap['indices'][n]
            best = min(range(16), key=lambda index:
                       sum((value[c] - PALETTE[index][c])**2 for c in range(3)))
            require(actual == best, f'Color quantization differs from source at {x},{y}')
            delta = [value[c] - PALETTE[actual][c] for c in range(3)]
            for dx, dy, weight in ((step, 0, 7), (-step, 1, 3), (0, 1, 5), (step, 1, 1)):
                nx, ny = x + dx, y + dy
                if 0 <= nx < width and ny < height and bitmap['alpha'][ny * width + nx]:
                    for channel in range(3):
                        errors[ny][nx][channel] += delta[channel] * weight / 16


def verify_app_monikers(resources, source_dir):
    require('AppIconMonikersResource' in resources, 'Application icon resource missing')
    resource = resources['AppIconMonikersResource']
    chunks = read_chunks(resource)
    require(len(chunks) == 9, 'Expected seven graphical monikers plus token text and token list')
    # Format requirements expressed independently of the source generator.
    # width, height, bpp, DisplaySize, DisplayAspectRatio, DisplayClass,
    # original artwork, original positive mask, preview label.
    variants = [(48, 30, 4, 1, 0, 6, 'c48x30.bmp', 'a48x30.bmp', '48x30 color'),
                (48, 30, 1, 1, 0, 1, 'm48x30.bmp', 'n48x30.bmp', '48x30 mono'),
                (32, 20, 4, 0, 0, 6, 'c32x20.bmp', 'a32x20.bmp', '32x20 color'),
                (32, 20, 1, 0, 0, 1, 'm32x20.bmp', 'n32x20.bmp', '32x20 mono'),
                (64, 40, 4, 2, 0, 6, 'c64x40.bmp', 'a64x40.bmp', '64x40 color'),
                (64, 40, 1, 2, 0, 1, 'm64x40.bmp', 'n64x40.bmp', '64x40 mono'),
                (48, 14, 1, 1, 2, 1, 'm48x14.bmp', 'n48x14.bmp', '48x14 CGA')]
    decoded = []
    graphic_chunks = [chunk for chunk in chunks if chunk['data'][0] & 0xc0 == 0x40]
    require(len(graphic_chunks) == 7, 'Expected exactly seven graphical application monikers')
    for chunk in graphic_chunks:
        raw = chunk['data']
        require(len(raw) >= 15, 'Truncated application moniker')
        moniker_type, width, height = struct.unpack_from('<BHH', raw)
        require(moniker_type & 0xc0 == 0x40, 'Moniker does not contain a GString')
        require(raw[5] == 81, 'Expected GR_DRAW_BITMAP_CP in moniker')
        size = word(raw, 6)
        require(len(raw) == 8 + size + 1 and raw[-1] == 0,
                'GString bitmap size or end opcode is invalid')
        bitmap = decode_bitmap(raw[8:-1])
        require(bitmap['masked'], 'Application icon must have a mask')
        require((bitmap['width'], bitmap['height']) == (width, height),
                'Cached moniker dimensions differ from bitmap')
        decoded.append((chunk, bitmap, moniker_type))
    images, report, expected_entries = [], [], set()
    for width, height, bits, display_size, aspect, color, artwork, maskfile, label in variants:
        matches = [(chunk, bitmap, kind) for chunk, bitmap, kind in decoded
                   if (bitmap['width'], bitmap['height'], bitmap['bits']) == (width, height, bits)]
        require(len(matches) == 1, label + ': missing or ambiguous moniker')
        chunk, bitmap, kind = matches[0]
        require(kind == 0x40 | (aspect << 4) | color, label + ': incorrect moniker type')
        original = Image.open(source_dir / artwork).convert('RGB')
        mask = Image.open(source_dir / maskfile).convert('RGB')
        require(original.size == mask.size == (width, height), label + ': source dimensions differ')
        for y in range(height):
            for x in range(width):
                n = y * width + x
                source_mask = mask.getpixel((x, y))
                require(source_mask in ((0, 0, 0), (255, 255, 255)), 'Non-binary source mask')
                require(bitmap['alpha'][n] == (source_mask == (255, 255, 255)),
                        label + f': mask differs at {x},{y}')
                if bits == 1 and bitmap['alpha'][n]:
                    require(PALETTE[bitmap['indices'][n]] == original.getpixel((x, y)),
                            label + f': monochrome pixel differs at {x},{y}')
        if bits == 4:
            verify_color_policy(bitmap, original)
        list_type = (display_size << 12) | (3 << 8) | 0xc0 | (aspect << 4) | color
        expected_entries.add((list_type, chunk['handle'], 0x1000 | resource['id']))
        images.append((label, bitmap['image']))
        report.append(dict(variant=label, source=artwork, source_mask=maskfile,
                           chunk_handle=chunk['handle'], resource_offset=chunk['offset'],
                           width=width, height=height, bits_per_pixel=bits,
                           moniker_type=hex(kind), list_type=hex(list_type),
                           opaque_pixels=sum(bitmap['alpha']), pixels_checked=width * height,
                           native_bitmap_sha256=hashlib.sha256(chunk['data'][8:-1]).hexdigest()))
    token_lists = [chunk for chunk in chunks if chunk['size'] == 48 and chunk['data'][0] & 0x80]
    require(len(token_lists) == 1, 'Token database moniker list missing or ambiguous')
    token_entries = list(struct.iter_unpack('<3H', token_lists[0]['data']))
    # This is a general LMem data resource, so Glue emits ordinary geode handle
    # relocations here. Object-block moniker lists below instead use deferred
    # ObjRelocationID source markers and are relocated by the object system.
    token_expected = {(kind, handle, resource['id']) for kind, handle, target in expected_entries}
    require(set(token_entries[1:]) == token_expected,
            'Token database moniker list contains incorrect native chunk references or types')
    require(token_entries[0][0] == 0x81 and token_entries[0][2] == resource['id'],
            'Token database text fallback type or block is invalid')
    for entry in range(8):
        handle_offset = token_lists[0]['offset'] + 6 * entry + 4
        require((0x23, 0, handle_offset) in resource['relocation_records'],
                'Token moniker list optr has no owning-geode handle relocation')
    token_text = {chunk['handle']: chunk['data'] for chunk in chunks}.get(token_entries[0][1], b'')
    require(b'GNU Chess 6.3.0\0' in token_text, 'Token database title fallback missing')
    # Verify both actual compiled moniker lists point at these chunks and carry
    # the correct resolution/aspect/style metadata. ObjRelocationID source 1
    # means owning-geode resource; source 4 means the current block.
    for name in ('AppResource', 'Interface'):
        lists = [chunk for chunk in read_chunks(resources[name], icon_resource=False)
                 if chunk['size'] == 48 and chunk['data'][0] & 0x80]
        matching = []
        for chunk in lists:
            entries = list(struct.iter_unpack('<3H', chunk['data']))
            if set(entries[1:]) == expected_entries:
                matching.append(entries)
        require(len(matching) == 1, name + ': native moniker list is absent or points at wrong icons')
        first = matching[0][0]
        require(first[0] == 0x81, name + ': text fallback missing')
        target = resources[name] if first[2] == 0x4000 else resources['AppResource']
        require(first[2] in (0x4000, 0x1000 | resources['AppResource']['id']),
                name + ': text fallback resource invalid')
        text_chunks = {c['handle']: c['data'] for c in read_chunks(target, icon_resource=False)}
        require(b'GNU Chess 6.3.0\0' in text_chunks.get(first[1], b''), name + ': text fallback title missing')
    return images, report


def font(size):
    try:
        return ImageFont.truetype('DejaVuSans.ttf', size)
    except OSError:
        return ImageFont.load_default()


def preview(pieces, app_images, output):
    # Reconstruct only the drawing data/orientation, not the GEOS application UI.
    # A 2x view maps the 24-unit piece footprint to its full 48 native pixels.
    # Keep those decoded pixels intact instead of clipping a 48px image into
    # the old 24px drawing rectangle or implying a different hit-test layout.
    board = Image.new('RGB', (528, 528), 'white')
    drawing = ImageDraw.Draw(board)
    position = 'RNBQKBNR' + 'P' * 8 + ' ' * 32 + 'p' * 8 + 'rnbqkbnr'
    for rank in range(8):
        for file in range(8):
            x, y = 40 + file * 56, 16 + (7 - rank) * 56
            gray = 255 if (rank + file) & 1 else 170
            drawing.rectangle((x, y, x + 56, y + 56), fill=(gray, gray, gray), outline='black', width=2)
            piece = position[rank * 8 + file]
            if piece != ' ':
                board.paste(pieces[piece], (x + 4, y + 4), pieces[piece])
        drawing.text((10, 16 + (7 - rank) * 56 + 16), str(rank + 1), fill='black', font=font(20))
    for file in range(8):
        drawing.text((60 + file * 56, 470), chr(97 + file), fill='black', font=font(20))
    drawing.text((40, 498), '48px pieces at 24 logical units (2x view)', fill='black', font=font(17))
    canvas = Image.new('RGB', (1224, 910), '#f4f1e9')
    draw = ImageDraw.Draw(canvas)
    draw.text((24, 16), 'GNU Chess: decoded native icon resources', fill='#192a31', font=font(25))
    draw.text((24, 51), 'Host reconstruction from gnuchess.geo — not a GEOS runtime screenshot',
              fill='#394a50', font=font(18))
    canvas.paste(board.resize((792, 792), Image.Resampling.NEAREST), (20, 94))
    draw.text((842, 95), 'Application monikers', fill='#192a31', font=font(20))
    for i, (label, icon) in enumerate(app_images):
        x, y = 852 + (i % 2) * 175, 142 + (i // 2) * 132
        scale = min(3, 155 // icon.width, 92 // icon.height)
        enlarged = icon.resize((icon.width * scale, icon.height * scale), Image.Resampling.NEAREST)
        canvas.paste(enlarged, (x, y), enlarged)
        draw.text((x, y + 98), label, fill='#394a50', font=font(13))
    draw.text((842, 712), 'All twelve piece bitmaps', fill='#192a31', font=font(19))
    for i, (character, icon) in enumerate(pieces.items()):
        x, y = 844 + (i % 6) * 56, 750 + (i // 6) * 60
        draw.rectangle((x, y, x + 52, y + 52), fill='white' if i < 6 else '#aaaaaa')
        enlarged = icon.resize((48, 48), Image.Resampling.NEAREST)
        canvas.paste(enlarged, (x + 2, y + 2), enlarged)
    output.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(output)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--geo', type=Path, default=ROOT / 'dist/gnuchess.geo')
    parser.add_argument('--map', type=Path, default=ROOT / 'logs/glue.log')
    parser.add_argument('--json', type=Path, default=ROOT / 'dist/icon-test-report.json')
    parser.add_argument('--preview', type=Path, default=ROOT / 'dist/embedded-icons-preview.png')
    args = parser.parse_args()
    try:
        data = args.geo.read_bytes()
        resources = read_resources(data, args.map.read_text())
        require('ChessPieces' in resources, 'Linked executable has no ChessPieces resource')
        pieces, piece_report = verify_pieces(resources['ChessPieces'], ROOT / 'assets/pieces',
                                            (ROOT / 'src/geos/gnuchess.goc').read_text())
        app_images, app_report = verify_app_monikers(resources, ROOT / 'assets/application')
        preview(pieces, app_images, args.preview)
        report = dict(icon_resource_validation='PASS', geos_runtime_tested=False,
                      geo_sha256=hashlib.sha256(data).hexdigest(),
                      pieces=piece_report, application_monikers=app_report,
                      piece_pixels_checked=sum(item['pixels_checked'] for item in piece_report),
                      piece_logical_footprint=[24, 24],
                      resource_flags={name:hex(resources[name]['flags'])
                                      for name in ('ChessPieces', 'AppIconMonikersResource')},
                      preview=str(args.preview.relative_to(ROOT)),
                      preview_kind='Host reconstruction of executable bitmaps; not a GEOS screenshot',
                      scope='Actual linked resource headers, chunks, pixels, masks and moniker list; UI piece mapping inspected in GOC source')
        args.json.parent.mkdir(parents=True, exist_ok=True)
        args.json.write_text(json.dumps(report, indent=2) + '\n')
        print(f"PASS: {len(piece_report)} linked piece bitmaps; {report['piece_pixels_checked']} source pixels/mask values verified")
        print(f'PASS: {len(app_report)} linked application monikers and display-selection entries')
        print('PASS: shared, read-only, movable LMem icon resources and chunk bounds')
        print('Preview: ' + str(args.preview))
        print('GEOS execution/UI/loader behavior: NOT TESTED')
        print('SHA-256: ' + report['geo_sha256'])
    except (ValueError, OSError, KeyError, struct.error) as exc:
        raise SystemExit('FAIL: ' + str(exc))


if __name__ == '__main__':
    main()
